steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'install']
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['spring-boot:run']

options:
  logging: gs://mycoolapp-logs-bucket
  serviceAccount: true-velocity-424421-a9@appspot.gserviceaccount.com

timeout: '600s'

