name: Run Postman Tests

on: [push, pull_request]

jobs:
  newman-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Newman
      run: npm install -g newman

    - name: Run Postman Collection
      run: newman run postman/ContactList.collection.json -e postman/ContactList.environment.json
